title: $_

github: 
  username: andresfredes

social:
  name: Andres Fredes
  email: contact@af-mail.aleeas.com

baseurl: ""
url: "https://andresfredes.github.io"

toc: true

remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme